#!/bin/bash
echo "⚡ ENERGY GRID SECURITY"
echo "======================="
echo ""
echo "Checking grid systems..."
echo "✅ SCADA controller verified"
echo "🚨 Unauthorized access detected"
echo "✅ Grid protected from blackout"
echo ""
echo "Energy infrastructure secure."
