#!/usr/bin/env luajit
--[[
  MOABI Generated LuaJIT FFI Caller
  Auto-generated by moabi-libify
]]

local ffi = require('ffi')

-- Function declarations
ffi.cdef[[
]]

local lib_path = '/mnt/d/moabi/test_binaries/curl.so'
local lib = ffi.load(lib_path)

-- PIE binary: addresses are relative to load base

-- Symbol table
local SYMBOLS = {
}

local function get_func(name)
    local ok, f = pcall(function() return lib[name] end)
    if ok and f then return f end
    return nil
end

local function list_functions()
    print('\nAvailable functions:')
    for name, addr in pairs(SYMBOLS) do
        print(string.format('  0x%016x  %s', addr, name))
    end
end

print('')
print('MOABI Libify - Direct Binary Access')
print('====================================')
print('Library: ' .. lib_path)
print('Functions discovered: 0')
list_functions()
print('')
