#!/usr/bin/env luajit
--[[
  MOABI Generated LuaJIT FFI Caller
  Auto-generated by moabi-libify
]]

local ffi = require('ffi')

-- Function declarations
ffi.cdef[[
    void* _start();  // addr=0x100e4c0
    void* __zig_probe_stack();  // addr=0x1040350
    void* memset();  // addr=0x1040490
    void* memcpy();  // addr=0x1040390
    void* log();  // addr=0x1040220
    void* getauxval();  // addr=0x1013180
]]

local lib_path = '/mnt/d/moabi/test_binaries/entropy.so'
local lib = ffi.load(lib_path)

-- Non-PIE binary, original base: 0x1000000

-- Symbol table
local SYMBOLS = {
    ['__anon_1519'] = 0x1008ad1,
    ['__anon_1582'] = 0x1008fef,
    ['__anon_1535'] = 0x1008c5f,
    ['__anon_3917'] = 0x10094b5,
    ['__anon_2372'] = 0x1008c73,
    ['__anon_3200'] = 0x10032e0,
    ['__anon_4557'] = 0x1009111,
    ['__anon_3456'] = 0x1003378,
    ['__anon_2381'] = 0x100906d,
    ['__anon_3546'] = 0x1008d40,
    ['__anon_1589'] = 0x1008b62,
    ['__anon_2408'] = 0x1009b46,
    ['__anon_2458'] = 0x1009ba6,
    ['__anon_2509'] = 0x1009bdb,
    ['__anon_2594'] = 0x1009b7d,
    ['__anon_1525'] = 0x1008aac,
    ['__anon_2439'] = 0x10094a2,
    ['__anon_2586'] = 0x1009afc,
    ['__anon_2602'] = 0x1009b27,
    ['__anon_10058'] = 0x1009aad,
    ['__anon_3811'] = 0x1009b59,
    ['__anon_3783'] = 0x100980b,
    ['__anon_15368'] = 0x10096f8,
    ['__anon_3791'] = 0x1009af7,
    ['__anon_12243'] = 0x1004fe0,
    ['__anon_10212'] = 0x10096a9,
    ['__anon_10220'] = 0x10096d2,
    ['__anon_8942'] = 0x1009adb,
    ['__anon_3988'] = 0x10034b8,
    ['__anon_3992'] = 0x1008cb6,
    ['__anon_4013'] = 0x1003550,
    ['__anon_4596'] = 0x1008bb4,
    ['__anon_4758'] = 0x100927d,
    ['__anon_4625'] = 0x1008dbe,
    ['__anon_4654'] = 0x10093e8,
    ['__anon_4682'] = 0x1009402,
    ['__anon_3997'] = 0x1009252,
    ['__anon_3237'] = 0x1008a40,
    ['__anon_9391'] = 0x10097fb,
    ['__anon_15230'] = 0x1009882,
    ['__anon_15244'] = 0x100981d,
    ['__anon_15265'] = 0x1009995,
    ['__anon_15275'] = 0x1009934,
    ['__anon_15301'] = 0x10099f2,
    ['__anon_22116'] = 0x1008f21,
    ['__anon_22121'] = 0x1009189,
    ['__anon_12164'] = 0x10097f3,
    ['__anon_7967'] = 0x1008ceb,
    ['__anon_3288'] = 0x1009cf5,
    ['__anon_6645'] = 0x10037e8,
    ['__anon_2364'] = 0x1008c0b,
    ['__anon_10437'] = 0x1009238,
    ['__anon_6778'] = 0x10096b7,
    ['__anon_6821'] = 0x1009039,
    ['__anon_6843'] = 0x1008dde,
    ['__anon_6851'] = 0x1008af2,
    ['__anon_6857'] = 0x1008c9b,
    ['__anon_6866'] = 0x1008bd0,
    ['__anon_6873'] = 0x1009334,
    ['__anon_6882'] = 0x1008ca6,
    ['__anon_6890'] = 0x1008c41,
    ['__anon_6897'] = 0x1008ba4,
    ['__anon_6904'] = 0x1008b94,
    ['__anon_6910'] = 0x1008da6,
    ['__anon_6917'] = 0x1008c34,
    ['__anon_6924'] = 0x100935d,
    ['__anon_6931'] = 0x1009353,
    ['__anon_6938'] = 0x1008d98,
    ['__anon_7189'] = 0x10090c5,
    ['__anon_7184'] = 0x10090b3,
    ['__anon_7275'] = 0x100955a,
    ['__anon_7222'] = 0x10091c4,
    ['__anon_7255'] = 0x10090c2,
    ['__anon_6836'] = 0x10097de,
    ['__anon_17930'] = 0x10080f0,
    ['__anon_8600'] = 0x10096ec,
    ['__anon_11396'] = 0x1008fd9,
    ['__anon_8863'] = 0x10096f0,
    ['__anon_11400'] = 0x1008fe4,
    ['__anon_8869'] = 0x100981a,
    ['__anon_8882'] = 0x1009cf4,
    ['__anon_8926'] = 0x10096a7,
    ['__anon_11368'] = 0x1008fd3,
    ['__anon_11398'] = 0x1008fc8,
    ['__anon_11390'] = 0x1008fa4,
    ['__anon_11376'] = 0x1008f9e,
    ['__anon_11392'] = 0x1008f98,
    ['__anon_11386'] = 0x1008fbc,
    ['__anon_11372'] = 0x1008fb6,
    ['__anon_11374'] = 0x1008faa,
    ['__anon_11382'] = 0x1008fde,
    ['__anon_11370'] = 0x1008fc2,
    ['__anon_11378'] = 0x1008f92,
    ['__anon_11394'] = 0x1008f8c,
    ['__anon_11380'] = 0x1008fe9,
    ['__anon_11388'] = 0x1008fb0,
    ['__anon_11384'] = 0x1008fcd,
    ['__anon_11758'] = 0x1009a87,
    ['__anon_11770'] = 0x1009a60,
    ['__anon_11747'] = 0x1009c03,
    ['__anon_11764'] = 0x1009a44,
    ['__anon_11752'] = 0x1009a1f,
    ['__anon_17494'] = 0x10098e3,
    ['__anon_12051'] = 0x1004fd8,
    ['__anon_8856'] = 0x1008a68,
    ['__anon_8875'] = 0x10097e0,
    ['__anon_11647'] = 0x1009c62,
    ['__anon_11654'] = 0x1009cb2,
    ['__anon_15472'] = 0x10096b2,
    ['__anon_15475'] = 0x1009698,
    ['__anon_3573'] = 0x100926a,
    ['__anon_18158'] = 0x10097d9,
    ['__anon_16469'] = 0x100953b,
    ['__anon_8932'] = 0x1009c38,
    ['__anon_22927'] = 0x1009ab9,
    ['_start'] = 0x100e4c0,
    ['__zig_probe_stack'] = 0x1040350,
    ['memset'] = 0x1040490,
    ['memcpy'] = 0x1040390,
    ['log'] = 0x1040220,
    ['getauxval'] = 0x1013180,
}

local function get_func(name)
    local ok, f = pcall(function() return lib[name] end)
    if ok and f then return f end
    return nil
end

local function list_functions()
    print('\nAvailable functions:')
    for name, addr in pairs(SYMBOLS) do
        print(string.format('  0x%016x  %s', addr, name))
    end
end

print('')
print('MOABI Libify - Direct Binary Access')
print('====================================')
print('Library: ' .. lib_path)
print('Functions discovered: 6')
list_functions()
print('')
