#!/usr/bin/env luajit
--[[
  MOABI Generated LuaJIT FFI Caller
  Auto-generated by moabi-libify
]]

local ffi = require('ffi')

-- Function declarations
ffi.cdef[[
    void* _start();  // addr=0x100c370
    void* __zig_probe_stack();  // addr=0x103f110
    void* memset();  // addr=0x103f250
    void* memcpy();  // addr=0x103f150
    void* log();  // addr=0x103efd0
    void* getauxval();  // addr=0x10111f0
]]

local lib_path = '/mnt/d/moabi/test_binaries/entropy-dynamic.so'
local lib = ffi.load(lib_path)

-- Non-PIE binary, original base: 0x1000000

-- Symbol table
local SYMBOLS = {
    ['__anon_1519'] = 0x1006909,
    ['__anon_1582'] = 0x1006e27,
    ['__anon_1535'] = 0x1006a97,
    ['__anon_3917'] = 0x10072ed,
    ['__anon_2372'] = 0x1006aab,
    ['__anon_3200'] = 0x10404b0,
    ['__anon_4557'] = 0x1006f49,
    ['__anon_3456'] = 0x1040548,
    ['__anon_2381'] = 0x1006ea5,
    ['__anon_3546'] = 0x1006b78,
    ['__anon_1589'] = 0x100699a,
    ['__anon_2408'] = 0x100797e,
    ['__anon_2458'] = 0x10079de,
    ['__anon_2509'] = 0x1007a13,
    ['__anon_2594'] = 0x10079b5,
    ['__anon_1525'] = 0x10068e4,
    ['__anon_2439'] = 0x10072da,
    ['__anon_2586'] = 0x1007934,
    ['__anon_2602'] = 0x100795f,
    ['__anon_10058'] = 0x10078e5,
    ['__anon_3811'] = 0x1007991,
    ['__anon_3783'] = 0x1007643,
    ['__anon_15368'] = 0x1007530,
    ['__anon_3791'] = 0x100792f,
    ['__anon_12243'] = 0x1040658,
    ['__anon_10212'] = 0x10074e1,
    ['__anon_10220'] = 0x100750a,
    ['__anon_8942'] = 0x1007913,
    ['__anon_3988'] = 0x1001c60,
    ['__anon_3992'] = 0x1006aee,
    ['__anon_4013'] = 0x1001cf8,
    ['__anon_4596'] = 0x10069ec,
    ['__anon_4758'] = 0x10070b5,
    ['__anon_4625'] = 0x1006bf6,
    ['__anon_4654'] = 0x1007220,
    ['__anon_4682'] = 0x100723a,
    ['__anon_3997'] = 0x100708a,
    ['__anon_3237'] = 0x1006878,
    ['__anon_9391'] = 0x1007633,
    ['__anon_15230'] = 0x10076ba,
    ['__anon_15244'] = 0x1007655,
    ['__anon_15265'] = 0x10077cd,
    ['__anon_15275'] = 0x100776c,
    ['__anon_15301'] = 0x100782a,
    ['__anon_22116'] = 0x1006d59,
    ['__anon_22121'] = 0x1006fc1,
    ['__anon_12164'] = 0x100762b,
    ['__anon_7967'] = 0x1006b23,
    ['__anon_3288'] = 0x1007b2d,
    ['__anon_6645'] = 0x1001ef8,
    ['__anon_2364'] = 0x1006a43,
    ['__anon_10437'] = 0x1007070,
    ['__anon_6778'] = 0x10074ef,
    ['__anon_6821'] = 0x1006e71,
    ['__anon_6843'] = 0x1006c16,
    ['__anon_6851'] = 0x100692a,
    ['__anon_6857'] = 0x1006ad3,
    ['__anon_6866'] = 0x1006a08,
    ['__anon_6873'] = 0x100716c,
    ['__anon_6882'] = 0x1006ade,
    ['__anon_6890'] = 0x1006a79,
    ['__anon_6897'] = 0x10069dc,
    ['__anon_6904'] = 0x10069cc,
    ['__anon_6910'] = 0x1006bde,
    ['__anon_6917'] = 0x1006a6c,
    ['__anon_6924'] = 0x1007195,
    ['__anon_6931'] = 0x100718b,
    ['__anon_6938'] = 0x1006bd0,
    ['__anon_7189'] = 0x1006efd,
    ['__anon_7184'] = 0x1006eeb,
    ['__anon_7275'] = 0x1007392,
    ['__anon_7222'] = 0x1006ffc,
    ['__anon_7255'] = 0x1006efa,
    ['__anon_6836'] = 0x1007616,
    ['__anon_17930'] = 0x1006780,
    ['__anon_8600'] = 0x1007524,
    ['__anon_11396'] = 0x1006e11,
    ['__anon_8863'] = 0x1007528,
    ['__anon_11400'] = 0x1006e1c,
    ['__anon_8869'] = 0x1007652,
    ['__anon_8882'] = 0x1007b2c,
    ['__anon_8926'] = 0x10074df,
    ['__anon_11368'] = 0x1006e0b,
    ['__anon_11398'] = 0x1006e00,
    ['__anon_11390'] = 0x1006ddc,
    ['__anon_11376'] = 0x1006dd6,
    ['__anon_11392'] = 0x1006dd0,
    ['__anon_11386'] = 0x1006df4,
    ['__anon_11372'] = 0x1006dee,
    ['__anon_11374'] = 0x1006de2,
    ['__anon_11382'] = 0x1006e16,
    ['__anon_11370'] = 0x1006dfa,
    ['__anon_11378'] = 0x1006dca,
    ['__anon_11394'] = 0x1006dc4,
    ['__anon_11380'] = 0x1006e21,
    ['__anon_11388'] = 0x1006de8,
    ['__anon_11384'] = 0x1006e05,
    ['__anon_11758'] = 0x10078bf,
    ['__anon_11770'] = 0x1007898,
    ['__anon_11747'] = 0x1007a3b,
    ['__anon_11764'] = 0x100787c,
    ['__anon_11752'] = 0x1007857,
    ['__anon_17494'] = 0x100771b,
    ['__anon_12051'] = 0x1003688,
    ['__anon_8856'] = 0x10068a0,
    ['__anon_8875'] = 0x1007618,
    ['__anon_11647'] = 0x1007a9a,
    ['__anon_11654'] = 0x1007aea,
    ['__anon_15472'] = 0x10074ea,
    ['__anon_15475'] = 0x10074d0,
    ['__anon_3573'] = 0x10070a2,
    ['__anon_18158'] = 0x1007611,
    ['__anon_16469'] = 0x1007373,
    ['__anon_8932'] = 0x1007a70,
    ['__anon_22927'] = 0x10078f1,
    ['_start'] = 0x100c370,
    ['__zig_probe_stack'] = 0x103f110,
    ['memset'] = 0x103f250,
    ['memcpy'] = 0x103f150,
    ['log'] = 0x103efd0,
    ['getauxval'] = 0x10111f0,
}

local function get_func(name)
    local ok, f = pcall(function() return lib[name] end)
    if ok and f then return f end
    return nil
end

local function list_functions()
    print('\nAvailable functions:')
    for name, addr in pairs(SYMBOLS) do
        print(string.format('  0x%016x  %s', addr, name))
    end
end

print('')
print('MOABI Libify - Direct Binary Access')
print('====================================')
print('Library: ' .. lib_path)
print('Functions discovered: 6')
list_functions()
print('')
