#!/usr/bin/env luajit
--[[
  MOABI Generated LuaJIT FFI Caller
  Auto-generated by moabi-libify
]]

local ffi = require('ffi')

-- Function declarations
ffi.cdef[[
    void* _obstack_newchunk();  // addr=0xdca0
    void* _obstack_begin_1();  // addr=0xdc80
    void* _obstack_allocated_p();  // addr=0xde40
    void* _obstack_begin();  // addr=0xdc60
    void* _obstack_memory_used();  // addr=0xdf10
    void* _obstack_free();  // addr=0xde80
]]

local lib_path = '/mnt/d/moabi/test_binaries/ls.so'
local lib = ffi.load(lib_path)

-- PIE binary: addresses are relative to load base

-- Symbol table
local SYMBOLS = {
    ['obstack_alloc_failed_handler'] = 0x230a0,
    ['_obstack_newchunk'] = 0xdca0,
    ['_obstack_begin_1'] = 0xdc80,
    ['_obstack_allocated_p'] = 0xde40,
    ['_obstack_begin'] = 0xdc60,
    ['_obstack_memory_used'] = 0xdf10,
    ['_obstack_free'] = 0xde80,
}

local function get_func(name)
    local ok, f = pcall(function() return lib[name] end)
    if ok and f then return f end
    return nil
end

local function list_functions()
    print('\nAvailable functions:')
    for name, addr in pairs(SYMBOLS) do
        print(string.format('  0x%016x  %s', addr, name))
    end
end

print('')
print('MOABI Libify - Direct Binary Access')
print('====================================')
print('Library: ' .. lib_path)
print('Functions discovered: 6')
list_functions()
print('')
