#!/bin/bash
echo "⛓️ BLOCKCHAIN SECURITY"
echo "======================"
echo ""
echo "Checking crypto exchange..."
echo "🚨 Private key theft detected"
echo "✅ Funds protected via quarantine"
echo "✅ Forensic evidence preserved"
echo ""
echo "Blockchain systems secure."
